source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DSLibAlerts', :exclusive => true do
  pod 'DSLibCore', :path => "../../DSLibCore"
  pod "DSLibAlerts", :path => "../"
end

target 'Tests', :exclusive => true do
  pod 'DSLibCore', :path => "../../DSLibCore"
  pod "DSLibAlerts", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
