source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DSLibAlerts' do
  pod 'DSLibCore', :path => "../Submodules/DSLibCore"
  pod "DSLibAlerts", :path => "../"
  pod 'SystemWindowController', :path => "../Submodules/SystemWindowController"
end

target 'Tests' do
  pod 'DSLibCore', :path => "../Submodules/DSLibCore"
  pod "DSLibAlerts", :path => "../"
  pod 'SystemWindowController', :path => "../Submodules/SystemWindowController"
end
